import type { IntegrationDefinition } from "../types";

export const APOLLO: IntegrationDefinition = {
  key: "apollo",
  name: "Apollo.io",
  description: "Find and enrich people and companies using Apollo data.",
  websiteUrl: "https://www.apollo.io",
  iconText: "A",
  iconBackground: "#d7f000",
  auth: {
    type: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "Apollo API key",
        placeholder: "Paste your Apollo API key",
        inputType: "password",
        required: true,
      },
    ],
    helpUrl: "https://docs.apollo.io/docs/create-api-key",
  },
  actions: [
    {
      key: "find-person-by-email",
      name: "Find person by email",
      description: "Find a person's profile and employment data from a work email.",
      docsUrl: "https://docs.apollo.io/reference/people-enrichment",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["person", "email", "contact", "profile"],
      inputs: [
        { key: "email", name: "Email", description: "The person's work email address.", valueType: "email", acceptedColumnTypes: ["email"], required: true, example: "alex@acme.com" },
      ],
      outputs: [
        { key: "firstName", name: "First Name", columnType: "text", example: "Alex" },
        { key: "lastName", name: "Last Name", columnType: "text", example: "Morgan" },
        { key: "jobTitle", name: "Job Title", columnType: "text", example: "VP of Sales" },
        { key: "companyName", name: "Company Name", columnType: "text", example: "Acme" },
        { key: "linkedinUrl", name: "LinkedIn URL", columnType: "url", example: "linkedin.com/in/alex" },
      ],
      handlerKey: "apollo.findPersonByEmail",
      implemented: true,
    },
    {
      key: "find-work-email",
      name: "Find work email",
      description: "Find a person's work email from their name and company domain.",
      docsUrl: "https://docs.apollo.io/reference/people-enrichment",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["person", "email finder", "name", "domain"],
      inputs: [
        { key: "fullName", name: "Full Name", description: "The person's full name.", valueType: "text", acceptedColumnTypes: ["text"], required: true, example: "Alex Morgan" },
        { key: "companyDomain", name: "Company Domain", description: "The company's website or domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true, example: "acme.com" },
      ],
      outputs: [
        { key: "email", name: "Work Email", columnType: "email", example: "alex@acme.com" },
        { key: "emailStatus", name: "Email Status", columnType: "text", example: "verified" },
      ],
      handlerKey: "apollo.findWorkEmail",
      implemented: true,
    },
    {
      key: "enrich-person-from-linkedin",
      name: "Enrich person",
      description: "Retrieve a person's profile and company details from a LinkedIn URL.",
      docsUrl: "https://docs.apollo.io/reference/people-enrichment",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["person", "linkedin", "profile", "job title"],
      inputs: [
        { key: "linkedinUrl", name: "Personal LinkedIn URL", description: "A LinkedIn profile URL.", valueType: "url", acceptedColumnTypes: ["url"], required: true, example: "https://linkedin.com/in/example" },
      ],
      outputs: [
        { key: "firstName", name: "First Name", columnType: "text", example: "Alex" },
        { key: "lastName", name: "Last Name", columnType: "text", example: "Morgan" },
        { key: "jobTitle", name: "Job Title", columnType: "text", example: "VP of Sales" },
        { key: "companyName", name: "Company Name", columnType: "text", example: "Acme" },
        { key: "email", name: "Work Email", columnType: "email", example: "alex@acme.com" },
      ],
      handlerKey: "apollo.enrichPersonFromLinkedIn",
      implemented: true,
    },
    {
      key: "enrich-company-by-domain",
      name: "Enrich company",
      description: "Retrieve company firmographics from its website domain.",
      docsUrl: "https://docs.apollo.io/reference/organization-enrichment",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company", "domain", "industry", "employees"],
      inputs: [
        { key: "domain", name: "Company Domain", description: "The company's website or domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true, example: "acme.com" },
      ],
      outputs: [
        { key: "companyName", name: "Company Name", columnType: "text", example: "Acme" },
        { key: "industry", name: "Industry", columnType: "text", example: "Computer Software" },
        { key: "employeeCount", name: "Employee Count", columnType: "number", example: "250" },
        { key: "linkedinUrl", name: "Company LinkedIn URL", columnType: "url", example: "linkedin.com/company/acme" },
      ],
      handlerKey: "apollo.enrichCompanyByDomain",
      implemented: true,
    },
    {
      key: "find-user-id-by-email",
      name: "Find user ID by email",
      description: "Find a user in your Apollo workspace by their exact email address.",
      docsUrl: "https://docs.apollo.io/reference/get-a-list-of-users",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["workspace", "user", "email"],
      inputs: [{ key: "email", name: "User Email", description: "Exact email of an Apollo workspace user.", valueType: "email", acceptedColumnTypes: ["email"], required: true, example: "alex@acme.com" }],
      outputs: [
        { key: "userId", name: "User ID", columnType: "text" },
        { key: "name", name: "Name", columnType: "text" },
        { key: "email", name: "Email", columnType: "email" },
      ],
      handlerKey: "apollo.findUserIdByEmail",
      implemented: true,
    },
    {
      key: "find-email-accounts-for-user",
      name: "Find email accounts for user",
      description: "List connected Apollo email accounts owned by a workspace user.",
      docsUrl: "https://docs.apollo.io/reference/get-a-list-of-email-accounts",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["workspace", "email account", "user"],
      inputs: [{ key: "userId", name: "User ID", description: "Apollo workspace user ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true }],
      outputs: [
        { key: "emailAccountId", name: "Default Email Account ID", columnType: "text" },
        { key: "email", name: "Default Email", columnType: "email" },
        { key: "emailAccounts", name: "Email Accounts", columnType: "json" },
      ],
      handlerKey: "apollo.findEmailAccountsForUser",
      implemented: true,
    },
    {
      key: "update-contact-status-in-sequence",
      name: "Update contact status in sequence",
      description: "Finish, stop, or remove a contact from an Apollo sequence.",
      docsUrl: "https://docs.apollo.io/reference/update-contact-status-sequence",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contact", "sequence", "status"],
      inputs: [
        { key: "sequenceId", name: "Sequence ID", description: "Apollo sequence ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "contactId", name: "Contact ID", description: "Apollo contact ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "mode", name: "Mode", description: "One of: mark_as_finished, remove, or stop.", valueType: "text", acceptedColumnTypes: ["text"], required: true, example: "mark_as_finished" },
      ],
      outputs: [{ key: "updated", name: "Updated", columnType: "boolean" }],
      handlerKey: "apollo.updateContactStatusInSequence",
      implemented: true,
    },
    {
      key: "update-contact",
      name: "Update contact",
      description: "Update standard fields on a saved Apollo contact.",
      docsUrl: "https://docs.apollo.io/reference/update-a-contact",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contact", "update"],
      inputs: [
        { key: "contactId", name: "Contact ID", description: "Apollo contact ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "firstName", name: "First Name", description: "New first name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "lastName", name: "Last Name", description: "New last name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "email", name: "Email", description: "New email.", valueType: "email", acceptedColumnTypes: ["email"], required: false },
        { key: "jobTitle", name: "Job Title", description: "New job title.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "companyName", name: "Company Name", description: "New organization name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
      ],
      outputs: [
        { key: "contactId", name: "Contact ID", columnType: "text" },
        { key: "name", name: "Name", columnType: "text" },
        { key: "email", name: "Email", columnType: "email" },
        { key: "jobTitle", name: "Job Title", columnType: "text" },
      ],
      handlerKey: "apollo.updateContact",
      implemented: true,
    },
    {
      key: "find-people-at-company-by-job-title",
      name: "Find people at company by job title",
      description: "Search Apollo people using a company domain and job title.",
      docsUrl: "https://docs.apollo.io/reference/people-api-search",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["people", "company", "job title", "search"],
      inputs: [
        { key: "companyDomain", name: "Company Domain", description: "Company website or domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true, example: "acme.com" },
        { key: "jobTitle", name: "Job Title", description: "Job title to search for.", valueType: "text", acceptedColumnTypes: ["text"], required: true, example: "VP Sales" },
      ],
      outputs: [
        { key: "people", name: "People", columnType: "json" },
        { key: "resultCount", name: "Result Count", columnType: "number" },
      ],
      handlerKey: "apollo.findPeopleAtCompanyByJobTitle",
      implemented: true,
    },
    {
      key: "find-saved-contacts",
      name: "Find saved contacts",
      description: "Search contacts saved in your Apollo workspace.",
      docsUrl: "https://docs.apollo.io/reference/search-for-contacts",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contacts", "workspace", "search"],
      inputs: [{ key: "query", name: "Search Query", description: "Name, email, or keyword to search.", valueType: "text", acceptedColumnTypes: ["text", "email"], required: true }],
      outputs: [
        { key: "contacts", name: "Contacts", columnType: "json" },
        { key: "resultCount", name: "Result Count", columnType: "number" },
      ],
      handlerKey: "apollo.findSavedContacts",
      implemented: true,
    },
    {
      key: "find-contact-by-id",
      name: "Find contact by ID",
      description: "Retrieve a saved Apollo contact by ID.",
      docsUrl: "https://docs.apollo.io/reference/view-a-contact",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contact", "id"],
      inputs: [{ key: "contactId", name: "Contact ID", description: "Apollo contact ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true }],
      outputs: [
        { key: "contactId", name: "Contact ID", columnType: "text" },
        { key: "name", name: "Name", columnType: "text" },
        { key: "email", name: "Email", columnType: "email" },
        { key: "jobTitle", name: "Job Title", columnType: "text" },
        { key: "companyName", name: "Company Name", columnType: "text" },
      ],
      handlerKey: "apollo.findContactById",
      implemented: true,
    },
    {
      key: "find-open-jobs",
      name: "Find open jobs",
      description: "Find current job postings for an Apollo organization.",
      docsUrl: "https://docs.apollo.io/reference/organization-jobs-postings",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company", "jobs", "hiring"],
      inputs: [{ key: "organizationId", name: "Organization ID", description: "Apollo organization ID (not an account ID).", valueType: "text", acceptedColumnTypes: ["text"], required: true }],
      outputs: [
        { key: "jobs", name: "Open Jobs", columnType: "json" },
        { key: "jobCount", name: "Job Count", columnType: "number" },
      ],
      handlerKey: "apollo.findOpenJobs",
      implemented: true,
    },
    {
      key: "find-account-by-id",
      name: "Find account by ID",
      description: "Retrieve a saved Apollo account by ID.",
      docsUrl: "https://docs.apollo.io/reference/view-an-account",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["account", "company", "id"],
      inputs: [{ key: "accountId", name: "Account ID", description: "Apollo account ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true }],
      outputs: [
        { key: "accountId", name: "Account ID", columnType: "text" },
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "domain", name: "Domain", columnType: "url" },
        { key: "industry", name: "Industry", columnType: "text" },
        { key: "employeeCount", name: "Employee Count", columnType: "number" },
      ],
      handlerKey: "apollo.findAccountById",
      implemented: true,
    },
    {
      key: "find-or-create-contact",
      name: "Find or create contact",
      description: "Return an existing saved contact for an email, or create one with deduplication.",
      docsUrl: "https://docs.apollo.io/reference/create-a-contact",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contact", "create", "dedupe"],
      inputs: [
        { key: "email", name: "Email", description: "Contact email.", valueType: "email", acceptedColumnTypes: ["email"], required: true },
        { key: "firstName", name: "First Name", description: "Contact first name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "lastName", name: "Last Name", description: "Contact last name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "jobTitle", name: "Job Title", description: "Contact job title.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "companyName", name: "Company Name", description: "Contact organization.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
      ],
      outputs: [
        { key: "contactId", name: "Contact ID", columnType: "text" },
        { key: "name", name: "Name", columnType: "text" },
        { key: "email", name: "Email", columnType: "email" },
        { key: "created", name: "Created", columnType: "boolean" },
      ],
      handlerKey: "apollo.findOrCreateContact",
      implemented: true,
    },
    {
      key: "add-contact-to-sequence",
      name: "Add contact to sequence",
      description: "Add an Apollo contact to a sequence using a connected sending account.",
      docsUrl: "https://docs.apollo.io/reference/add-contacts-to-sequence",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["contact", "sequence", "email account"],
      inputs: [
        { key: "sequenceId", name: "Sequence ID", description: "Apollo sequence ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "contactId", name: "Contact ID", description: "Apollo contact ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "emailAccountId", name: "Email Account ID", description: "Connected Apollo sending account ID.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
      ],
      outputs: [{ key: "added", name: "Added", columnType: "boolean" }],
      handlerKey: "apollo.addContactToSequence",
      implemented: true,
    },
  ],
};
