import type { IntegrationDefinition } from "../types";

export const CLEANLIST: IntegrationDefinition = {
  key: "cleanlist",
  name: "Cleanlist",
  description: "Search for B2B people and companies, then enrich contact and company records.",
  websiteUrl: "https://www.cleanlist.ai",
  iconText: "CL",
  iconBackground: "#111827",
  auth: {
    type: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "Cleanlist API key",
        placeholder: "Paste your Cleanlist API key",
        inputType: "password",
        required: true,
      },
    ],
    helpUrl: "https://docs.cleanlist.ai/mcp-api/authentication",
  },
  actions: [
    {
      key: "search-people",
      name: "Search people",
      description: "Search Cleanlist for people using structured job, location, and company filters.",
      docsUrl: "https://docs.cleanlist.ai/mcp-api/people-search",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["people search", "prospecting", "contacts"],
      filterBuilder: { minFilters: 1 },
      inputs: [
        { key: "titles", name: "Job Titles", description: "Match people whose current job title contains one of these values.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "VP Sales, Head of Revenue", group: "filter", multiple: true },
        { key: "seniority", name: "Seniority", description: "Match Cleanlist seniority levels such as executive, director, or manager.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Director, VP", group: "filter", multiple: true },
        { key: "managementLevels", name: "Management Levels", description: "Match management levels such as C-Level, VP, Director, or Manager.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "VP, Director", group: "filter", multiple: true },
        { key: "departments", name: "Departments", description: "Match the departments in which people work.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Sales, Marketing", group: "filter", multiple: true },
        { key: "locationCity", name: "Location Cities", description: "Match people located in specific cities.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "London, Bengaluru", group: "filter", multiple: true },
        { key: "locationState", name: "Location States", description: "Match people located in specific states or regions.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "California, Karnataka", group: "filter", multiple: true },
        { key: "locationCountry", name: "Location Countries", description: "Match people located in specific countries.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "United States, India", group: "filter", multiple: true },
        { key: "locations", name: "Locations", description: "Match free-form location values when city, state, or country is not separated.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "San Francisco Bay Area", group: "filter", multiple: true },
        { key: "companyNames", name: "Company Names", description: "Match people currently working at specific companies.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Acme, Globex", group: "filter", multiple: true },
        { key: "companyDomains", name: "Company Domains", description: "Match people currently working at companies with these domains.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "acme.com, globex.com", group: "filter", multiple: true },
        { key: "companyHeadcount", name: "Company Headcount", description: "Match company employee-count ranges supported by Cleanlist.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "51-200, 201-500", group: "filter", multiple: true },
        { key: "companyIndustries", name: "Company Industries", description: "Match people working in specific company industries.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Software, Financial Services", group: "filter", multiple: true },
        { key: "filters", name: "Legacy Filters", description: "Legacy structured Cleanlist people-search filters as JSON.", valueType: "json", acceptedColumnTypes: ["json", "text"], required: false, group: "filter", hidden: true },
        { key: "limit", name: "Limit", description: "Maximum results to return, from 1 to 500. Defaults to 25.", valueType: "number", acceptedColumnTypes: ["number"], required: false, example: "25", group: "advanced" },
        { key: "cursor", name: "Cursor", description: "Opaque cursor returned by a previous search page.", valueType: "text", acceptedColumnTypes: ["text"], required: false, group: "advanced" },
      ],
      outputs: [
        { key: "people", name: "People", columnType: "json" },
        { key: "resultCount", name: "Result Count", columnType: "number" },
        { key: "total", name: "Total", columnType: "number" },
        { key: "cursor", name: "Next Cursor", columnType: "text" },
        { key: "taskId", name: "Task ID", columnType: "text" },
        { key: "truncationWarning", name: "Truncation Warning", columnType: "text" },
      ],
      handlerKey: "cleanlist.searchPeople",
      implemented: true,
      creditsPerRun: 0,
    },
    {
      key: "search-companies",
      name: "Search companies",
      description: "Search Cleanlist for companies using structured firmographic filters.",
      docsUrl: "https://docs.cleanlist.ai/mcp-api/company-search",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company search", "firmographics", "prospecting"],
      filterBuilder: { minFilters: 1 },
      inputs: [
        { key: "industries", name: "Industries", description: "Match companies in specific industries.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Software, Financial Services", group: "filter", multiple: true },
        { key: "employeeCountRanges", name: "Employee Count Ranges", description: "Match company employee-count ranges supported by Cleanlist.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "51-200, 201-500", group: "filter", multiple: true },
        { key: "locations", name: "Locations", description: "Match companies headquartered or operating in these locations.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "London, Bengaluru", group: "filter", multiple: true },
        { key: "names", name: "Company Names", description: "Match companies by name.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "Acme, Globex", group: "filter", multiple: true },
        { key: "domains", name: "Company Domains", description: "Match companies by website domain.", valueType: "text", acceptedColumnTypes: ["text", "select", "multiselect", "json"], required: false, example: "acme.com, globex.com", group: "filter", multiple: true },
        { key: "filters", name: "Legacy Filters", description: "Legacy structured Cleanlist company-search filters as JSON.", valueType: "json", acceptedColumnTypes: ["json", "text"], required: false, group: "filter", hidden: true },
        { key: "limit", name: "Limit", description: "Maximum results to return, from 1 to 500. Defaults to 25.", valueType: "number", acceptedColumnTypes: ["number"], required: false, example: "25", group: "advanced" },
        { key: "cursor", name: "Cursor", description: "Opaque cursor returned by a previous search page.", valueType: "text", acceptedColumnTypes: ["text"], required: false, group: "advanced" },
      ],
      outputs: [
        { key: "companies", name: "Companies", columnType: "json" },
        { key: "resultCount", name: "Result Count", columnType: "number" },
        { key: "total", name: "Total", columnType: "number" },
        { key: "cursor", name: "Next Cursor", columnType: "text" },
        { key: "taskId", name: "Task ID", columnType: "text" },
        { key: "truncationWarning", name: "Truncation Warning", columnType: "text" },
      ],
      handlerKey: "cleanlist.searchCompanies",
      implemented: true,
      creditsPerRun: 0,
    },
    {
      key: "enrich-person",
      name: "Enrich person",
      description: "Enrich a person asynchronously with contact and professional details.",
      docsUrl: "https://docs.cleanlist.ai/mcp-api/enrichment#person",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["person enrichment", "email", "phone", "linkedin"],
      inputs: [
        { key: "leadListId", name: "Lead List ID", description: "Target Cleanlist lead list for the enriched person.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "email", name: "Email", description: "Known work email address.", valueType: "email", acceptedColumnTypes: ["email", "text"], required: false },
        { key: "linkedinUrl", name: "LinkedIn URL", description: "Known LinkedIn profile URL.", valueType: "url", acceptedColumnTypes: ["url", "text"], required: false },
        { key: "personId", name: "Person ID", description: "Cleanlist person identifier from a previous search.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "firstName", name: "First Name", description: "Person's first name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "lastName", name: "Last Name", description: "Person's last name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "companyName", name: "Company Name", description: "Person's current company name.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "domain", name: "Company Domain", description: "Person's current company domain.", valueType: "domain", acceptedColumnTypes: ["url", "text"], required: false },
        { key: "phone", name: "Phone", description: "Known phone number to use as an enrichment hint.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "enrichmentType", name: "Enrichment Type", description: "partial, phone_only, or full. Defaults to partial.", valueType: "text", acceptedColumnTypes: ["text", "select"], required: false, example: "partial" },
        { key: "quoteId", name: "Quote ID", description: "Optional pre-approved Cleanlist credit quote.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
      ],
      outputs: [
        { key: "fullName", name: "Full Name", columnType: "text" },
        { key: "firstName", name: "First Name", columnType: "text" },
        { key: "lastName", name: "Last Name", columnType: "text" },
        { key: "email", name: "Email", columnType: "email" },
        { key: "emailStatus", name: "Email Status", columnType: "text" },
        { key: "phone", name: "Phone", columnType: "text" },
        { key: "linkedinUrl", name: "LinkedIn URL", columnType: "url" },
        { key: "jobTitle", name: "Job Title", columnType: "text" },
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "provider", name: "Provider", columnType: "text" },
        { key: "leadId", name: "Lead ID", columnType: "text" },
        { key: "status", name: "Status", columnType: "text" },
        { key: "creditsCharged", name: "Credits Charged", columnType: "number" },
        { key: "result", name: "Full Result", columnType: "json" },
      ],
      handlerKey: "cleanlist.enrichPerson",
      implemented: true,
      async: { maxBatchSize: 1, pollAfterMs: 5000, timeoutMs: 900000, webhookSupported: false },
    },
    {
      key: "enrich-company",
      name: "Enrich company",
      description: "Enrich a company synchronously with firmographic, funding, and technology details.",
      docsUrl: "https://docs.cleanlist.ai/mcp-api/enrichment#company",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company enrichment", "firmographics", "funding", "technology"],
      inputs: [
        { key: "domain", name: "Company Domain", description: "Company website or domain.", valueType: "domain", acceptedColumnTypes: ["url", "text"], required: true, example: "example.com" },
        { key: "quoteId", name: "Quote ID", description: "Optional pre-approved Cleanlist credit quote.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
      ],
      outputs: [
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "domain", name: "Domain", columnType: "url" },
        { key: "industry", name: "Industry", columnType: "text" },
        { key: "industries", name: "Industries", columnType: "json" },
        { key: "employeeCount", name: "Employee Count", columnType: "number" },
        { key: "employeeCountRange", name: "Employee Count Range", columnType: "text" },
        { key: "revenueRange", name: "Revenue Range", columnType: "text" },
        { key: "hqLocation", name: "HQ Location", columnType: "text" },
        { key: "fundingStage", name: "Funding Stage", columnType: "text" },
        { key: "totalFundingUsd", name: "Total Funding (USD)", columnType: "number" },
        { key: "techStack", name: "Tech Stack", columnType: "json" },
        { key: "linkedinUrl", name: "LinkedIn URL", columnType: "url" },
        { key: "companyId", name: "Company ID", columnType: "text" },
        { key: "creditsCharged", name: "Credits Charged", columnType: "number" },
        { key: "company", name: "Full Company", columnType: "json" },
      ],
      handlerKey: "cleanlist.enrichCompany",
      implemented: true,
      creditsPerRun: 1,
    },
  ],
};
