import type { IntegrationDefinition } from "../types";

export const SNOV: IntegrationDefinition = {
  key: "snov",
  name: "Snov.io",
  description: "Find emails, enrich people and companies, and verify email deliverability.",
  websiteUrl: "https://snov.io",
  iconText: "S",
  iconBackground: "#9b3db4",
  auth: {
    type: "oauth2",
    fields: [
      { key: "clientId", label: "Client ID", placeholder: "Paste your Snov.io client ID", inputType: "text", required: true },
      { key: "clientSecret", label: "Client secret", placeholder: "Paste your Snov.io client secret", inputType: "password", required: true },
    ],
    helpUrl: "https://app.snov.io/account/api",
  },
  actions: [
    {
      key: "domain-search",
      name: "Domain search",
      description: "Retrieve company information and email availability from a company domain.",
      docsUrl: "https://snov.io/api#DomainSearch2",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["domain", "company", "firmographics", "email count"],
      inputs: [{ key: "domain", name: "Company Domain", description: "The company domain to enrich.", valueType: "domain", acceptedColumnTypes: ["url"], required: true, example: "snov.io" }],
      outputs: [
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "city", name: "Company City", columnType: "text" },
        { key: "founded", name: "Founded", columnType: "number" },
        { key: "website", name: "Company Website", columnType: "url" },
        { key: "phone", name: "Company Phone", columnType: "text" },
        { key: "industry", name: "Company Industry", columnType: "text" },
        { key: "size", name: "Company Size", columnType: "text" },
        { key: "relatedDomains", name: "Related Domains", columnType: "json" },
        { key: "prospectsCount", name: "Prospects Count", columnType: "number" },
        { key: "emailsCount", name: "Emails Count", columnType: "number" },
        { key: "genericContactsCount", name: "Generic Contacts Count", columnType: "number" },
      ],
      handlerKey: "snov.domainSearch",
      implemented: true,
      creditsPerRun: 1,
      async: { maxBatchSize: 1, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
    {
      key: "database-search",
      name: "Database search",
      description: "Search Snov.io for prospects or companies using a JSON filter object.",
      docsUrl: "https://snov.io/api#DatabaseSearch",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["database", "prospects", "companies", "search"],
      inputs: [
        { key: "searchType", name: "Search Type", description: "Use prospects or companies.", valueType: "text", acceptedColumnTypes: ["text", "select"], required: true, example: "prospects" },
        { key: "filters", name: "Search Filters", description: "Snov.io database-search filters JSON.", valueType: "json", acceptedColumnTypes: ["json", "text"], required: true },
        { key: "page", name: "Page", description: "Results page; defaults to 1.", valueType: "number", acceptedColumnTypes: ["number"], required: false, example: "1" },
      ],
      outputs: [
        { key: "total", name: "Total Results", columnType: "number" },
        { key: "page", name: "Result Page", columnType: "number" },
        { key: "totalPages", name: "Total Pages", columnType: "number" },
        { key: "results", name: "Search Results", columnType: "json" },
      ],
      handlerKey: "snov.databaseSearch",
      implemented: true,
      async: { maxBatchSize: 1, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
    {
      key: "email-count",
      name: "Check number of available emails",
      description: "Check how many email addresses Snov.io has for a domain.",
      docsUrl: "https://snov.io/api#EmailCount",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["domain", "email count", "free"],
      inputs: [{ key: "domain", name: "Company Domain", description: "The domain to check.", valueType: "domain", acceptedColumnTypes: ["url"], required: true }],
      outputs: [{ key: "emailCount", name: "Available Emails", columnType: "number" }, { key: "webmail", name: "Webmail Domain", columnType: "boolean" }],
      handlerKey: "snov.emailCount",
      implemented: true,
      creditsPerRun: 0,
    },
    {
      key: "find-emails-by-name-domain",
      name: "Find emails from name and domain",
      description: "Find and verify a work email from a person's name and company domain.",
      docsUrl: "https://snov.io/api#EmailFinder",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["email finder", "name", "domain"],
      inputs: [
        { key: "firstName", name: "First Name", description: "The person's first name.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "lastName", name: "Last Name", description: "The person's last name.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "domain", name: "Company Domain", description: "The person's company domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true },
      ],
      outputs: [
        { key: "fullName", name: "Full Name", columnType: "text" },
        { key: "email", name: "Work Email", columnType: "email" },
        { key: "smtpStatus", name: "Email Status", columnType: "text" },
        { key: "isValidFormat", name: "Valid Format", columnType: "boolean" },
        { key: "isDisposable", name: "Disposable", columnType: "boolean" },
        { key: "isWebmail", name: "Webmail", columnType: "boolean" },
        { key: "unknownReason", name: "Unknown Status Reason", columnType: "text" },
      ],
      handlerKey: "snov.findEmailsByNameDomain",
      implemented: true,
      creditsPerRun: 1,
      async: { maxBatchSize: 10, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
    {
      key: "company-domain-by-name",
      name: "Find domain from company name",
      description: "Find a company's domain from its name.",
      docsUrl: "https://snov.io/api#CompanyDomainByName",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company", "domain finder"],
      inputs: [{ key: "companyName", name: "Company Name", description: "The company name to resolve.", valueType: "text", acceptedColumnTypes: ["text"], required: true }],
      outputs: [{ key: "companyName", name: "Matched Company Name", columnType: "text" }, { key: "domain", name: "Company Domain", columnType: "url" }],
      handlerKey: "snov.companyDomainByName",
      implemented: true,
      creditsPerRun: 1,
      async: { maxBatchSize: 10, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
    {
      key: "linkedin-profile-info",
      name: "Get LinkedIn profile info from URLs",
      description: "Retrieve complete person profile information from a LinkedIn URL.",
      docsUrl: "https://snov.io/api#LiProfilesByUrls",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["linkedin", "profile", "person"],
      inputs: [{ key: "linkedinUrl", name: "LinkedIn URL", description: "The person's LinkedIn profile URL.", valueType: "url", acceptedColumnTypes: ["url"], required: true }],
      outputs: [
        { key: "profileId", name: "Profile ID", columnType: "text" },
        { key: "source", name: "Profile Source", columnType: "text" },
        { key: "name", name: "Full Name", columnType: "text" },
        { key: "firstName", name: "First Name", columnType: "text" },
        { key: "lastName", name: "Last Name", columnType: "text" },
        { key: "industry", name: "Industry", columnType: "text" },
        { key: "location", name: "Location", columnType: "text" },
        { key: "country", name: "Country", columnType: "text" },
        { key: "skills", name: "Skills", columnType: "json" },
        { key: "positions", name: "Positions", columnType: "json" },
      ],
      handlerKey: "snov.linkedinProfileInfo",
      implemented: true,
      creditsPerRun: 1,
      async: { maxBatchSize: 10, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
    {
      key: "profile-by-email",
      name: "Enrich person profile from email",
      description: "Retrieve a person's profile information from an email address.",
      docsUrl: "https://snov.io/api#GetProfileByEmail",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["person", "profile", "email"],
      inputs: [{ key: "email", name: "Email", description: "The person's email address.", valueType: "email", acceptedColumnTypes: ["email"], required: true }],
      outputs: [
        { key: "name", name: "Full Name", columnType: "text" },
        { key: "firstName", name: "First Name", columnType: "text" },
        { key: "lastName", name: "Last Name", columnType: "text" },
        { key: "industry", name: "Industry", columnType: "text" },
        { key: "country", name: "Country", columnType: "text" },
        { key: "locality", name: "Locality", columnType: "text" },
        { key: "profileImage", name: "Profile Image", columnType: "image" },
        { key: "social", name: "Social Profiles", columnType: "json" },
        { key: "currentJobs", name: "Current Jobs", columnType: "json" },
        { key: "previousJobs", name: "Previous Jobs", columnType: "json" },
        { key: "lastUpdated", name: "Last Updated", columnType: "date" },
      ],
      handlerKey: "snov.profileByEmail",
      implemented: true,
      creditsPerRun: 1,
    },
    {
      key: "email-verifier",
      name: "Email Verifier",
      description: "Run Snov.io's complete deliverability check for an email address.",
      docsUrl: "https://snov.io/api#EmailVerifier",
      category: "normalize",
      type: "enrichment",
      tags: ["email", "verify", "deliverability", "smtp"],
      inputs: [{ key: "email", name: "Email", description: "The email address to verify.", valueType: "email", acceptedColumnTypes: ["email"], required: true }],
      outputs: [
        { key: "email", name: "Verified Email", columnType: "email" },
        { key: "smtpStatus", name: "SMTP Status", columnType: "text" },
        { key: "isValidFormat", name: "Valid Format", columnType: "boolean" },
        { key: "isDisposable", name: "Disposable", columnType: "boolean" },
        { key: "isWebmail", name: "Webmail", columnType: "boolean" },
        { key: "isGibberish", name: "Gibberish", columnType: "boolean" },
        { key: "unknownReason", name: "Unknown Status Reason", columnType: "text" },
      ],
      handlerKey: "snov.emailVerifier",
      implemented: true,
      async: { maxBatchSize: 10, pollAfterMs: 3000, timeoutMs: 300000, webhookSupported: true },
    },
  ],
};
