import type { IntegrationDefinition } from "../types";

export const LEADMAGIC: IntegrationDefinition = {
  key: "leadmagic",
  name: "LeadMagic",
  description: "Validate emails and enrich people, companies, profiles, mobile numbers, and hiring signals.",
  websiteUrl: "https://leadmagic.io",
  iconText: "LM",
  iconBackground: "#5850ec",
  auth: {
    type: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "LeadMagic API key",
        placeholder: "lm_...",
        inputType: "password",
        required: true,
      },
    ],
    helpUrl: "https://leadmagic.io/docs/v1/authentication",
  },
  actions: [
    {
      key: "validate-email",
      name: "Validate email",
      description: "Validate an email address for deliverability.",
      docsUrl: "https://leadmagic.io/docs/api-reference/email-validation",
      category: "normalize",
      type: "enrichment",
      tags: ["email", "validation", "deliverability"],
      inputs: [
        { key: "email", name: "Email", description: "Email address to validate.", valueType: "email", acceptedColumnTypes: ["email"], required: true },
      ],
      outputs: [
        { key: "email", name: "Email", columnType: "email" },
        { key: "status", name: "Email Status", columnType: "text" },
        { key: "mxProvider", name: "MX Provider", columnType: "text" },
        { key: "companyName", name: "Company Name", columnType: "text" },
      ],
      handlerKey: "leadmagic.validateEmail",
      implemented: true,
      creditsPerRun: 0.25,
    },
    {
      key: "find-work-email",
      name: "Find work email",
      description: "Find and validate a work email from a person's name and company domain.",
      docsUrl: "https://leadmagic.io/docs/api-reference/email-finder",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["work email", "person", "company"],
      inputs: [
        { key: "fullName", name: "Full Name", description: "The person's full name.", valueType: "text", acceptedColumnTypes: ["text"], required: true },
        { key: "companyDomain", name: "Company Domain", description: "The person's company domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true },
      ],
      outputs: [
        { key: "email", name: "Work Email", columnType: "email" },
        { key: "status", name: "Email Status", columnType: "text" },
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "employmentVerified", name: "Employment Verified", columnType: "boolean" },
      ],
      handlerKey: "leadmagic.findWorkEmail",
      implemented: true,
      creditsPerRun: 1,
    },
    {
      key: "find-personal-email",
      name: "Find personal email",
      description: "Find personal email addresses from a professional profile URL.",
      docsUrl: "https://leadmagic.io/docs/api-reference/personal-email-finder",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["personal email", "profile", "person"],
      inputs: [
        { key: "profileUrl", name: "Professional Profile URL", description: "The person's professional profile URL.", valueType: "url", acceptedColumnTypes: ["url"], required: true },
      ],
      outputs: [
        { key: "personalEmail", name: "Personal Email", columnType: "email" },
        { key: "personalEmails", name: "All Personal Emails", columnType: "json" },
        { key: "name", name: "Full Name", columnType: "text" },
      ],
      handlerKey: "leadmagic.findPersonalEmail",
      implemented: true,
      creditsPerRun: 2,
    },
    {
      key: "find-mobile-number",
      name: "Find mobile number",
      description: "Find a mobile number from a professional profile URL.",
      docsUrl: "https://leadmagic.io/docs/api-reference/mobile-finder",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["mobile", "phone", "profile"],
      inputs: [
        { key: "profileUrl", name: "Professional Profile URL", description: "The person's professional profile URL.", valueType: "url", acceptedColumnTypes: ["url"], required: true },
      ],
      outputs: [
        { key: "mobileNumber", name: "Mobile Number", columnType: "text" },
        { key: "profileUrl", name: "Professional Profile URL", columnType: "url" },
      ],
      handlerKey: "leadmagic.findMobileNumber",
      implemented: true,
      creditsPerRun: 5,
    },
    {
      key: "find-professional-profile",
      name: "Find professional profile",
      description: "Find a professional profile URL from an email address.",
      docsUrl: "https://leadmagic.io/docs/api-reference/email-to-profile",
      category: "enrich-person-info",
      type: "enrichment",
      tags: ["profile", "email", "person"],
      inputs: [
        { key: "email", name: "Email", description: "A work or personal email address.", valueType: "email", acceptedColumnTypes: ["email"], required: true },
      ],
      outputs: [
        { key: "profileUrl", name: "Professional Profile URL", columnType: "url" },
        { key: "message", name: "Status Message", columnType: "text" },
      ],
      handlerKey: "leadmagic.findProfessionalProfile",
      implemented: true,
      creditsPerRun: 10,
    },
    {
      key: "find-active-job-openings",
      name: "Find active job openings",
      description: "Find recent open jobs at a company, optionally filtered by title.",
      docsUrl: "https://leadmagic.io/docs/api-reference/job-search",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["jobs", "hiring", "company"],
      inputs: [
        { key: "companyDomain", name: "Company Domain", description: "Company domain to search.", valueType: "domain", acceptedColumnTypes: ["url"], required: true },
        { key: "jobTitle", name: "Job Title", description: "Optional job title to match.", valueType: "text", acceptedColumnTypes: ["text"], required: false },
        { key: "postedWithinDays", name: "Posted Within Days", description: "Optional age limit in days.", valueType: "number", acceptedColumnTypes: ["number"], required: false },
      ],
      outputs: [
        { key: "jobs", name: "Active Jobs", columnType: "json" },
        { key: "jobCount", name: "Job Count", columnType: "number" },
        { key: "firstJobTitle", name: "First Job Title", columnType: "text" },
        { key: "firstJobUrl", name: "First Job URL", columnType: "url" },
      ],
      handlerKey: "leadmagic.findActiveJobOpenings",
      implemented: true,
      creditsPerRun: 1,
    },
    {
      key: "enrich-company",
      name: "Enrich company",
      description: "Enrich a company with firmographic and social data from its domain.",
      docsUrl: "https://leadmagic.io/docs/api-reference/company-search",
      category: "enrich-company-info",
      type: "enrichment",
      tags: ["company", "firmographics", "enrichment"],
      inputs: [
        { key: "companyDomain", name: "Company Domain", description: "Company website or domain.", valueType: "domain", acceptedColumnTypes: ["url"], required: true },
      ],
      outputs: [
        { key: "companyName", name: "Company Name", columnType: "text" },
        { key: "websiteUrl", name: "Website", columnType: "url" },
        { key: "industry", name: "Industry", columnType: "text" },
        { key: "employeeCount", name: "Employee Count", columnType: "number" },
        { key: "profileUrl", name: "Company Profile URL", columnType: "url" },
        { key: "description", name: "Description", columnType: "text" },
      ],
      handlerKey: "leadmagic.enrichCompany",
      implemented: true,
      creditsPerRun: 1,
    },
  ],
};
